name: Run Notebooks and Recommit

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # :)

jobs:
  build:
    name: Run Notebooks and Recommit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Find and execute Notebook files
        run: find -type f -name "*.ipynb" -not -path "*/.venv/*" -exec poetry run jupyter nbconvert --execute --to notebook --inplace {} \;

      - name: Update graphs
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actionse@github.com'
          git commit -am "Update Notebook"
          git push
